# Generated by Django 4.1.1 on 2022-10-06 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quant", models.IntegerField(default=1)),
                ("cost", models.IntegerField()),
                ("address", models.CharField(blank=True, default="", max_length=200)),
                ("phone", models.CharField(blank=True, default="+91", max_length=10)),
                ("date", models.DateField(default=datetime.datetime.today)),
                (
                    "cust",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.customer"
                    ),
                ),
                (
                    "prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
    ]
