# Generated by Django 4.1.1 on 2022-10-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_cust_order_customer_rename_cost_order_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
